# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mercadoria',
            fields=[
                ('merc_id', models.AutoField(primary_key=True, serialize=False)),
                ('cod_merc', models.IntegerField()),
                ('type_merc', models.CharField(max_length=40)),
                ('name_merc', models.CharField(max_length=40)),
                ('qntt_merc', models.FloatField()),
                ('price_merc', models.FloatField()),
                ('type_deal', models.CharField(choices=[('compra', 'Compra'), ('venda', 'Venda')], max_length=7)),
            ],
        ),
    ]
