# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mercadoria',
            old_name='cod_merc',
            new_name='codigo_mercadoria',
        ),
        migrations.RenameField(
            model_name='mercadoria',
            old_name='name_merc',
            new_name='nome_mercadoria',
        ),
        migrations.RenameField(
            model_name='mercadoria',
            old_name='price_merc',
            new_name='preco_mercadoria',
        ),
        migrations.RenameField(
            model_name='mercadoria',
            old_name='qntt_merc',
            new_name='quantidade_mercadoria',
        ),
        migrations.RenameField(
            model_name='mercadoria',
            old_name='type_merc',
            new_name='tipo_mercadoria',
        ),
        migrations.RenameField(
            model_name='mercadoria',
            old_name='type_deal',
            new_name='tipo_negocio',
        ),
    ]
